baseURL = "https://wicwik.github.io/"
title = "Welcome!"
theme = "LoveIt"
languageCode = "en-us"
languageName = "English"
pagination.pagerSize = 5

enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    pre = ""
    post = ""
    name = "All Posts"
    url = "/posts/"

    title = ""
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = "Categories"
  [[menu.main]]
    weight = 5
    identifier = "about"
    pre = "<b>"
    post = "</b>"
    name = "About"
    url = "/about/"
    title = "About"


[params]
  env = "production"
  defaultTheme = "dark"
  gitRepo = "https://github.com/Wicwik/wicwik.github.io"
  dateFormat = "January 2, 2006"
  title = "Welcome!"
  description = "Robert's personal blog"
  images = ["/undefined.png"]

  [params.author]
    name = "Róbert Belanec"
    email = "belanecrobert22@gmail.com"
    link = "https://wicwik.github.io/"
  
  [params.analytics]
    enable = true
    [params.analytics.google]
      id = "G-J2STH121Y3"
      anonymizeIP = true
  
  [params.cookieconsent]
    enable = true
    [params.cookieconsent.content]
      message = "This site uses Google Analytics."
      dismiss = "Allow cookies"
      link = "What are cookies?"

  [params.compatibility]
    polyfill = false
    objectFit = false

  
  [params.header]
    # behaviour of header toolbar
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      logo = "" 
      name = "Róbert Belanec"
      pre = ""
      post = ""
      typeit = false
  [params.footer]
    enable = true
    custom = ""
    hugo = false
    copyright = true
    author = true
    since = 2024
  [params.section]
    pagination.pagerSize = 10
    dateFormat = "January 2, 2006"
    rss = 10
  [params.list]
    pagination.pagerSize = 10
    dateFormat = "January 2, 2006"
    rss = 10
  [params.search]
    enable = true
    type = "lunr"
    contentLength = 4000
    placeholder = "Search..."
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false
  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      avatarURL = "/images/github.jpg"
      title = "Róbert Belanec"
      subtitle = "PhD student at <a href='https://kinit.sk' style='color:#bd3f50;'>kinit.sk</a>"
      typeit = true
      social = true
    [params.home.posts]
      enable = true
      pagination.pagerSize = 5
  [params.social]
    Github = "wicwik"
    Linkedin = "robertbelanec"
    RSS = "/index.xml"