baseURL = 'https://wicwik.github.io/'
title = 'PhD and stuff'
theme = 'LoveIt'
languageCode = 'en-us'
languageName = "English"
paginate = 5

enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[author]
  name = "Róbert Belanec"
  email = "belanecrobert22@gmail.com"
  link = "https://wicwik.github.io/"

[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    pre = ""
    post = ""
    name = "All Posts"
    url = "/posts/"

    title = ""
  [[menu.main]]
    weight = 5
    identifier = "about"
    pre = "<b>"
    post = "</b>"
    name = "About"
    url = "/about/"
    title = ""


[params]
  env = "production"
  defaultTheme = "dark"
  gitRepo = "https://github.com/Wicwik/wicwik.github.io"
  dateFormat = "January 2, 2006"
  title = "PhD and stuff"
  description = "Robert's Personal Blog"
  images = ["/undefined.png"]
  
  [params.header]
    # behaviour of header toolbar
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      logo = "" 
      name = "PhD and stuff"
      pre = ""
      post = ""
      typeit = false
  [params.footer]
    enable = true
    custom = ""
    hugo = false
    copyright = true
    author = true
    since = 2024
  [params.section]
    paginate = 10
    dateFormat = "January 2, 2006"
    rss = 10
  [params.list]
    paginate = 10
    dateFormat = "January 2, 2006"
    rss = 10
  [params.search]
    enable = true
    type = "lunr"
    contentLength = 4000
    placeholder = "Search..."
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false
  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      avatarURL = "/images/github.jpg"
      title = "Róbert Belanec"
      subtitle = "PhD student at <a href='https://kinit.sk' style='color:#bd3f50;'>kinit.sk</a>"
      typeit = true
      social = true
    [params.home.posts]
      enable = true
      paginate = 5
  [params.social]
    Github = "wicwik"
    Linkedin = "robertbelanec"
    RSS = "/index.xml"